/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wifllscheduler;

import org.apache.commons.cli.Options;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;

public class App {
    public String getGreeting() {
        return "wifflscheduler";
    }
    
    public static void main(String[] args) {
        
        ExcelFileReader excelFile = null;
        TeamList teams;
        Schedule schedule;
        String inputFilename = "";
        String outputFilename = "test.xlsx";
        Scheduler scheduler;
    
        
        // Process the command line
        Options options = new Options();
        options.addOption("i", "inputFile", true, "The name of the XLS Input file");
        options.addOption("o", "outputFile", true, "The name of the XLS Output file");

        CommandLineParser commandLineParser = new DefaultParser();
        CommandLine cmd;
        try {
            cmd = commandLineParser.parse(options, args);
            if (cmd.hasOption("i")) {
                inputFilename = cmd.getOptionValue("i");
            }
            if (cmd.hasOption("o")) {
                outputFilename = cmd.getOptionValue("o");
            }
        } catch ( Exception e) {
            System.out.println("Got exception " + e);
            System.exit(-1);
        }

        if (inputFilename.length() <= 0) {
            HelpFormatter formatter = new HelpFormatter();
            formatter.printHelp("wifllscheduler", options);
            System.exit(-1);
        }
        System.out.println("Processing the file: " + inputFilename);

        // Read the Excel file
        try {
            excelFile = new ExcelFileReader(inputFilename);
        } catch ( Exception e) {
            System.out.println("Got exception" + e);
            System.exit(-1);
        }

        scheduler = excelFile.getSchedulingData();
        // teams = new TeamList(24);
        teams = new TeamList(excelFile);
        System.out.println(new App().getGreeting());

        // Schedule the judging times
        schedule = new Schedule(scheduler, teams);
        // System.out.println(schedule);
        excelFile.updateScheduleTab(schedule);
        System.out.println("Processing out put file " + outputFilename);
        excelFile.createUpdatedWorkbook(outputFilename);
    }
}
